name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install depedencies
      run: sudo apt-get install -y
        gcc-multilib g++-multilib mingw-w64 wine64
    
    - name: Build 64 bits
      run: make clean; make demo
      
    - name: Build 32 bits
      run: make clean; make MSIZE='-m32' demo
      
      
    - name: Cross compiling for Win64
      run: make clean; ./mk-mingw.sh
