name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build 32/64 bits on Linux and cross compile for Windows

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install depedencies
      run: sudo apt-get install -y
        gcc-multilib g++-multilib mingw-w64 wine64

    - name: Build 64 bits
      run: make clean; make demo

    - name: build itself 64 bits (bootstrap)
      run: make cfront_c

    - name: Build 32 bits
      run: make clean; make MSIZE='-m32' demo

    - name: build itself 32 bits (bootstrap)
      run: rm cfront_c; make  MSIZE='-m32' cfront_c

    - name: Cross compiling for Win64
      run: make clean; ./mk-mingw.sh

    - name: build itself (bootstrap)
      run: ./mk-mingw.sh cfront_c.exe

  build-osx-amd64:
    name: cfront osx/amd64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    # build project amd64
    - name: build amd64
      run: make clean; make demo

    - name: build itself (bootstrap)
      run: make cfront_c
